// Generated by CoffeeScript 1.6.3
(function() {
  var controller;

  controller = function($scope) {};

  angular.module("odeskboardApp").controller("MainCtrl", ['$scope', controller]);

}).call(this);

/*
//@ sourceMappingURL=main.map
*/
