// Generated by CoffeeScript 1.6.3
(function() {
  var filter;

  filter = function() {
    return _.str.capitalize;
  };

  angular.module('odeskboardApp').filter('capital', filter);

}).call(this);

/*
//@ sourceMappingURL=capital.map
*/
