// Generated by CoffeeScript 1.6.2
(function() {
  var allFreelancers, cycle, jquery, keyword, lodash, pages, phantom, searchname, startTime, _,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  phantom = require("phantom");

  _ = require('lodash');

  jquery = "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js";

  lodash = "//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js";

  pages = 10000;

  cycle = 8000;

  keyword = 'photoshop';

  searchname = 'Nawal Magdy';

  allFreelancers = {};

  startTime = +new Date();

  phantom.create(function(ph) {
    var atEnd, callback, open, openLater;

    atEnd = function(all) {
      var endTime, minutes, seconds, time;

      console.log("" + searchname + " ranked " + all[searchname] + " for " + keyword);
      endTime = +new Date();
      time = Math.floor((endTime - startTime) / 1000);
      minutes = Math.floor(time / 60);
      seconds = time % 60;
      console.log("Time taken : " + minutes + " minutes " + seconds + " seconds.");
      return ph.exit();
    };
    callback = function(list, index, url) {
      var i, name, _i, _len;

      if (list) {
        for (i = _i = 0, _len = list.length; _i < _len; i = ++_i) {
          name = list[i];
          allFreelancers[name] = (index * list.length) + (i + 1);
        }
        if (__indexOf.call(list, searchname) >= 0) {
          console.log(url);
          return atEnd(allFreelancers);
        } else {
          console.log("Not yet found, " + index);
          return console.log('.');
        }
      }
    };
    openLater = function(url, callback) {
      return ph.createPage(function(page) {
        return page.open(url, function(status) {
          var onError;

          onError = function(result) {
            callback(result);
            return page.close();
          };
          return page.injectJs(jquery, function() {
            return page.injectJs(lodash, function() {
              return setTimeout((function() {
                var js, res;

                js = function() {
                  var h2Arr;

                  h2Arr = [];
                  $("h2 span[itemprop='name']").each(function() {
                    return h2Arr.push($(this).html());
                  });
                  return h2Arr;
                };
                res = page.evaluate(js, onError);
                if (res) {
                  callback(res);
                  return page.close();
                }
              }), cycle);
            });
          });
        });
      });
    };
    open = function(index, callback) {
      var url;

      url = "https://www.odesk.com/o/profiles/browse/?q=" + keyword;
      if (index > 1) {
        url = url + ("&page=" + index);
      }
      return openLater(url, function(list) {
        callback(list, index, url);
        if (index < pages) {
          return open(++index, callback);
        }
      });
    };
    return open(1, callback);
  });

}).call(this);

/*
//@ sourceMappingURL=odeskrank.map
*/
