// Generated by CoffeeScript 1.6.3
(function() {
  var addFreelancers, jquery, keyword, lodash, onError, page, phantom, url, _;

  phantom = require("phantom");

  _ = require('lodash');

  keyword = 'AngularJS';

  page = 1;

  url = "https://www.odesk.com/o/profiles/browse/?q=" + keyword + "&page=" + page;

  jquery = "http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js";

  lodash = "//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.min.js";

  addFreelancers = function(list) {
    list = _.flatten(list);
    return console.log(list);
  };

  onError = function(result) {
    console.log(result);
    return ph.exit();
  };

  phantom.create(function(ph) {
    return ph.createPage(function(page) {
      return page.open(url, function(status) {
        console.log("opened odesk? ", status);
        return page.injectJs(jquery, function() {
          return page.injectJs(lodash, function() {
            return setTimeout((function() {
              var js;
              js = function() {
                var h2Arr;
                h2Arr = [];
                $("h2 span[itemprop='name']").each(function() {
                  return h2Arr.push($(this).html());
                });
                return h2Arr;
              };
              return addFreelancers(page.evaluate(js, onError));
            }), 5000);
          });
        });
      });
    });
  });

}).call(this);

/*
//@ sourceMappingURL=odeskrank.map
*/
